---

- name: create nomad config
  template:
    src: nomad.hcl.j2
    dest: "{{ nomad_config_dir }}/nomad.hcl"

- name: create nomad service
  template:
    src: nomad.service.j2
    dest: /etc/systemd/system/nomad.service
  notify:
    - reload systemd
    - restart nomad
