---

- hosts: localhost
  gather_facts: yes
  tags: always
  tasks:
    - name: create timestamp file
      lineinfile:
        line: "started {{ ansible_date_time.iso8601_micro }}"
        dest: "/tmp/ansible.timestamp"
        create: yes
      changed_when: false
      tags: environment_status_reporting
    - name: Update apt-cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

- hosts: localhost
  roles:
    - { role: common, tags: common }
    - { role: consul, tags: consul }

- hosts: swarm_server
  roles:
    - { role: swarm, swarm_role: server }

- hosts: swarm_worker
  roles:
    - { role: swarm, swarm_role: worker }

- hosts: nomad_server
  roles:
    - { role: nomad, nomad_role: server }

- hosts: nomad_client
  roles:
    - { role: nomad, nomad_role: client }

- hosts: kubernetes_master
  roles:
    - { role: kubernetes, kubernetes_role: master }

- hosts: kubernetes_minion
  roles:
    - { role: kubernetes, kubernetes_role: minion }

- hosts: mysql
  roles:
    - { role: mysql }

- hosts: postgresql
  roles:
    - { role: postgresql }

- hosts: localhost
  tasks:
    - name: create timestamp file
      lineinfile:
        line: "completed {{ ansible_date_time.iso8601_micro }}"
        dest: "/tmp/ansible.timestamp"
        create: yes
      changed_when: false
      tags: environment_status_reporting
